### ISSUE TITLE
File never got closed in case something went wrong in block 

### ISSUE THREAD

**Issue by y9san9** [bpavuk/filery#1]
https://github.com/bpavuk/filery/blob/7f03720ab4697c39c5f1e3c0337a5c00b53d7031/src/commonMain/kotlin/com/bpavuk/filery/Filery.kt#L63-L67

Here is filery.block() throws any exception (including exceptions not related to IO), filery.close() will never got called. You should probably wrap the statement with try-finally closure:

```kotlin
try {
    filery.block()
} finally {
    filery.close()
}
```

**Comment by bpavuk** [comment]
Already fixed ☺️. Push will be soon
